version: 2.1
jobs:
  build:
    working_directory: ~/clojure-rest-api-quickstart
    docker:
    - image: circleci/clojure:openjdk-11-lein-2.9.5
      environment:
        TZ: Asia/Tokyo
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          curl -O https://download.clojure.org/install/linux-install-1.10.1.763.sh
          chmod +x linux-install-1.10.1.763.sh
          sudo ./linux-install-1.10.1.763.sh
    - restore_cache:
        key: minimal-api-lein-{{ checksum "minimal-api-lein/project.clj" }}
    - restore_cache:
        key: minimal-api-clj-{{ checksum "minimal-api-clj.core/deps.edn" }}
    - run: cd minimal-api-lein; lein deps
    - run: cd minimal-api-lein; lein test-coverage
    - run: cd minimal-api-clj.core; clojure -M:dev:test:cloverage
    - run: cd minimal-api-lein; lein lint
    - run: cd minimal-api-clj.core; clojure -M:eastwood
    - run:
        name: Install static code analysis tools
        environment:
          CLJSTYLE_VERSION: 0.14.0
          CLJ_KONDO_VERSION: 2020.12.12
          JOKER_VERSION: 0.15.7
        command: |
          # cljstyle
          wget https://github.com/greglook/cljstyle/releases/download/${CLJSTYLE_VERSION}/cljstyle_${CLJSTYLE_VERSION}_linux.tar.gz
          tar -xzf cljstyle_${CLJSTYLE_VERSION}_linux.tar.gz
          sudo mv -f cljstyle /usr/local/bin/
          # clj-kondo
          curl -sLO https://raw.githubusercontent.com/borkdude/clj-kondo/master/script/install-clj-kondo
          chmod +x install-clj-kondo
          sudo ./install-clj-kondo --version ${CLJ_KONDO_VERSION}
          # Joker
          wget https://github.com/candid82/joker/releases/download/v${JOKER_VERSION}/joker-${JOKER_VERSION}-linux-amd64.zip
          unzip -qq joker-${JOKER_VERSION}-linux-amd64.zip
          sudo mv -f joker /usr/local/bin/
    - run: cd minimal-api-lein; make lint
    - run: cd minimal-api-clj.core; make lint
    - run: bash <(curl -s https://codecov.io/bash) -f '!*.txt'
    - save_cache:
        key: minimal-api-lein-{{ checksum "minimal-api-lein/project.clj" }}
        paths:
        - ~/.lein
        - ~/.m2
    - save_cache:
        key: minimal-api-clj-{{ checksum "minimal-api-clj.core/deps.edn" }}
        paths:
        - ~/.cpcache
        - ~/.m2
    - run:
        name: Save test results
        command: |
          mkdir -p ~/test-results/lein-test
          if [ -f minimal-api-lein/target/coverage/junit.xml ]; then
            cp minimal-api-lein/target/coverage/junit.xml ~/test-results/lein-test/
          fi
          mkdir -p ~/test-results/clj-test
          if [ -f minimal-api-clj.core/target/coverage/junit.xml ]; then
            cp minimal-api-clj.core/target/coverage/junit.xml ~/test-results/clj-test/
          fi
        when: always
    - store_test_results:
        path: ~/test-results
