version: "3"
services:
  mysql:
    image: mysql:8.0.19
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: minimal_api_dev
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: minimal_api
      TZ: "Asia/Tokyo"

  mysql-test:
    image: mysql:8.0.19
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql-test-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: minimal_api_dev
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: minimal_api_test
      TZ: "Asia/Tokyo"

volumes:
  mysql-data:
    driver: local
  mysql-test-data:
    driver: local
